[bar.default]
center = [ "cat", "clock", "cat_2" ]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "battery" ]
font_weight = 400
hover_highlight = false
margin_edge = 4
margin_ends = 450
radius = 10
shadow = false
start = [ "workspaces", "warp", "media" ]
thickness = 30
widget_spacing = 12

[brightness]
minimum_brightness = 0.99999997764825821

[calendar]
enabled = true

    [calendar.account.hin]
    type = "google"

[colors]
mError = "#da4453"
mHover = "#3daee9"
mOnError = "#141618"
mOnHover = "#141618"
mOnPrimary = "#141618"
mOnSecondary = "#141618"
mOnSurface = "#fcfcfc"
mOnSurfaceVariant = "#a1a9b1"
mOnTertiary = "#141618"
mOutline = "#707d8a"
mPrimary = "#3daee9"
mSecondary = "#1d99f3"
mShadow = "#272c31"
mSurface = "#202224"
mSurfaceVariant = "#292d32"
mTertiary = "#9b59b6"

[config]

[control_center]
width = 800

    [control_center.calendar]
    show_week_numbers = true

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
enabled = [
    "noctalia/bongocat",
    "dotnetrob/cat",
    "levi/warp",
    "nightwatch75/file-search",
    "cleboost/jetbrains-provider",
    "kenn/keybind-cheatsheet",
    "ezequiel/mango_layouts",
    "davemhammer/obsidian",
    "noctalia/notes",
    "alexander/screen-toolkit",
    "davemhammer/tailscale",
    "noctalia/translator"
]

[shell]
avatar_path = "/home/hinne/Pictures/meme/cuoi-nham-hiem.jpeg"
font_family = "Maple Mono NF"
panel_anchor_bar = "default"
password_style = "random"
screen_time_enabled = true

    [shell.panel]
    borders = false
    shadow = false

    [shell.screenshot]
    directory = "/home/hinne/Pictures/Screenshots"

[sources]
enabled = true
name = "Noctalia Plugins"
url = "https://github.com/noctalia-dev/noctalia-plugins"

[templates]

[theme]
builtin = "Catppuccin"
community_palette = "One"
custom_palette = "Catppuccin Mocha"
mode = "dark"
source = "community"

    [theme.templates]
    builtin_ids = [ "cava", "gtk3", "gtk4", "kitty", "mango", "qt", "wezterm" ]
    community_ids = [
        "antigravity",
        "opencode",
        "brave",
        "discord",
        "telegram",
        "gimp",
        "neovim",
        "obsidian",
        "zed",
        "fuzzel",
        "obs",
        "fcitx5",
        "fzf",
        "yazi"
    ]

[wallpaper.default]
path = "/home/hinne/Pictures/Wallpapers/Wallpapers/fffkorobka-girls-last-tour.jpg"

[wallpaper.last]
path = "/home/hinne/Pictures/Wallpapers/Wallpapers/fffkorobka-girls-last-tour.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/hinne/Pictures/Wallpapers/Wallpapers/fffkorobka-girls-last-tour.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/hinne/Pictures/Wallpapers/Wallpapers/fffkorobka-girls-last-tour.jpg"

[widget.battery]
hide_when_full = true

[widget.brightness]
interactive = false

[widget.cat]
scale = 2.0
type = "noctalia/bongocat:cat"

[widget.cat_2]
scale = 1.9000000000000001
type = "dotnetrob/cat:cat"

[widget.media]
hide_when_no_media = true
show_progress = true

[widget.network]
show_label = false

[widget.tray]
drawer = true
drawer_columns = 4

[widget.volume]
show_label = false

[widget.warp]
type = "levi/warp:warp"

[widget.workspaces]
focused_output_only = true
style = "minimal"

[[states]]
enabled = false
name = "arch-updater"
sourceUrl = "https://github.com/noctalia-dev/noctalia-plugins"

[[states]]
enabled = false
name = "clipper"
sourceUrl = "https://github.com/noctalia-dev/noctalia-plugins"

[[states]]
enabled = false
name = "cloudflare-warp"
sourceUrl = "https://github.com/noctalia-dev/noctalia-plugins"

[[states]]
enabled = false
name = "polkit-agent"
sourceUrl = "https://github.com/noctalia-dev/noctalia-plugins"

[[states]]
enabled = true
name = "obsidian"
sourceUrl = "https://github.com/noctalia-dev/community-plugins"

[[states]]
enabled = true
name = "discord-voice"
sourceUrl = "https://github.com/noctalia-dev/community-plugins"

[[states]]
enabled = true
name = "tailscale"
sourceUrl = "https://github.com/noctalia-dev/community-plugins"

[[states]]
enabled = true
name = "screen-toolkit"
sourceUrl = "https://github.com/noctalia-dev/community-plugins"

[[states]]
enabled = true
name = "keybind-cheatsheet"
sourceUrl = "https://github.com/noctalia-dev/noctalia-plugins"

[[states]]
enabled = true
name = "ezequiel/mango_layouts"
sourceUrl = "https://github.com/noctalia-dev/community-plugins"
